# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: python -m pip install python-dateutil
- script: python -m pip install Docker
- script: python -m pip install requests
- script: python -m pip install colorama
- script: pwd
- task: Docker@0
  displayName: 'Build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Tenable_Conection'
    imageName: 'Prueba4:latest'

- task: Docker@0
  displayName: 'Publish image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Tenable_Conection'
    action: 'Push an image'
    imageName: 'Prueba4:latest'

- script: wget https://raw.githubusercontent.com/lobsanligo/test/master/csup.py 
- script: ls
- script: docker images --digests | grep prueba4 | awk '{print $3}' | awk -F ":" '{print $2}' > sha.txt
- script: ls
- script: cat sha.txt
- script: for i in $(cat sha.txt); do python $(pwd)/csup.py --access-key "f64f98a110bba8998a549a149c3e4db855fed2488ac0ff30065370ff381b00c2" --secret-key "cbfa9fc50d04389300ea61c6c740815fe54176889d00fcb84ea6401049b532a5" --consec-path registry.cloud.tenable.com  report $i; done 
- script: pwd && ls