# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:



- script: python -m pip install python-dateutil
- script: python -m pip install Docker
- script: python -m pip install requests
- script: python -m pip install colorama

- script: echo "7e271c68d031af8f39c8343421234cc7b88988921db2fadd333cdc13040fc2dc" > sha.txt
- script: wget https://pastebin.com/raw/e7uJZ92r -O xup.py
- script: for i in $(cat sha.txt); do python $(pwd)/xup.py --access-key "f64f98a110bba8998a549a149c3e4db855fed2488ac0ff30065370ff381b00c2" --secret-key "cbfa9fc50d04389300ea61c6c740815fe54176889d00fcb84ea6401049b532a5" --consec-path registry.cloud.tenable.com  report $i > report.txt; done 
- script: cat report.txt | grep Id | awk '{print $4}' > id.txt
- script: for i in $(cat id.txt); do python $(pwd)/xup.py --access-key "f64f98a110bba8998a549a149c3e4db855fed2488ac0ff30065370ff381b00c2" --secret-key "cbfa9fc50d04389300ea61c6c740815fe54176889d00fcb84ea6401049b532a5" --consec-path registry.cloud.tenable.com  policy $i; done 
- script: echo "pasó"